# Generated by Django 3.1.5 on 2021-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='/media/post_img/default.png', upload_to='OTH/media/'),
        ),
    ]
