# Generated by Django 3.1.5 on 2021-01-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20210125_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='/media/post_img', upload_to='OTH/media/'),
        ),
    ]
