# Generated by Django 3.1.5 on 2021-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20210117_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/default.png', upload_to='media/post_img/'),
        ),
    ]
