# Generated by Django 3.1.5 on 2021-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20210118_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_img/'),
        ),
    ]
