# Generated by Django 3.1.5 on 2021-01-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20210118_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='post_img/'),
        ),
    ]
