# Generated by Django 3.1.5 on 2021-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20210120_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/default.png', upload_to='post_img/'),
        ),
    ]
