# Generated by Django 3.1.5 on 2021-01-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_auto_20210120_1610'),
        ('Post', '0002_auto_20210119_2143'),
    ]

    operations = [
    ]
