# Generated by Django 3.1.5 on 2021-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20210121_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/default.png', upload_to='media/post_img/'),
        ),
    ]
