# Generated by Django 3.1.5 on 2021-02-11 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='', max_length=100)),
                ('account_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('info', models.TextField(default='Default info text', max_length=500)),
                ('save_percent', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('saving_time', models.IntegerField(default=12, help_text='Write here month amount for saving goal')),
                ('date', models.DateField(blank=True, default=datetime.date(2021, 2, 11), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date(2021, 2, 11), null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Insert a negative number if you are paying', max_digits=11)),
                ('move_to_account', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('moved_from_account', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('payee_payer', models.CharField(blank=True, default='default payer', max_length=50, null=True)),
                ('event', models.CharField(blank=True, max_length=14, null=True)),
                ('message', models.TextField(blank=True, default='This is a default text')),
                ('account_value_before', models.DecimalField(decimal_places=2, default=0, help_text='leave empty, generated automatically', max_digits=11)),
                ('account_value_after', models.DecimalField(decimal_places=2, default=0, help_text='leave empty, generated automatically', max_digits=11)),
                ('move_to_account_prestate', models.BooleanField(default=False, max_length=100)),
                ('second_account_movement_id', models.IntegerField(blank=True, default=None, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account_value')),
            ],
        ),
    ]
