# Generated by Django 3.1.5 on 2021-01-19 19:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('payee_payer', models.CharField(max_length=50)),
                ('event', models.CharField(choices=[('card', 'Card purchase'), ('save', 'Save'), ('o_transfer', 'Own transfer'), ('payment', 'Payment transfer'), ('deposit', 'Deposit')], max_length=10)),
                ('message', models.TextField(blank=True, default='This is a default text')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
