# Generated by Django 3.1.5 on 2021-02-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movements',
            name='move_to_account',
        ),
    ]
