# Generated by Django 3.1.5 on 2021-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='move_to_account',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'retirement'), ('2', 'travel'), ('3', 'linda'), ('4', 'eliasboss'), ('5', 'selma'), ('6', 'linda'), ('7', 'selma')], default=None, max_length=100, null=True),
        ),
    ]
