# Generated by Django 3.1.5 on 2021-02-08 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_movements_move_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 8), null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 8), null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='move_to_account',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
