# Generated by Django 3.1.5 on 2021-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_movements_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_value',
            name='account_name',
            field=models.CharField(default='Default account name', max_length=100),
        ),
    ]
