# Generated by Django 3.1.5 on 2021-01-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_value_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movements',
            name='user',
        ),
    ]
