# Generated by Django 3.1.5 on 2021-01-21 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210120_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_value',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='account_value',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movements',
            name='event',
            field=models.CharField(choices=[('card', 'Card purchase'), ('save', 'Save'), ('o_transfer_out', 'Own transfer(Send out)'), ('o_transfer_in', 'Own transfer(Send in)'), ('payment', 'Payment transfer'), ('deposit', 'Deposit')], max_length=14),
        ),
    ]
