# Generated by Django 3.1.5 on 2021-01-28 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210128_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 28, 20, 1, 7, 579940, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 28, 20, 1, 7, 580940, tzinfo=utc), null=True),
        ),
    ]
