# Generated by Django 3.1.5 on 2021-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_movements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_value',
            name='info',
            field=models.CharField(default='Default info text', max_length=500),
        ),
    ]
