# Generated by Django 3.1.5 on 2021-02-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210209_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='second_account_movement_id',
            field=models.IntegerField(default=0),
        ),
    ]
