# Generated by Django 3.1.5 on 2021-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210203_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='move_to_account',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'retirement500.00'), ('2', 'travel-90.00')], max_length=100, null=True),
        ),
    ]
