# Generated by Django 3.1.5 on 2021-01-22 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_value_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.TextField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
