# Generated by Django 3.1.5 on 2021-01-29 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210128_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 29, 8, 4, 26, 123084, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 29, 8, 4, 26, 123084, tzinfo=utc), null=True),
        ),
    ]
