# Generated by Django 3.1.5 on 2021-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_movements_second_account_movement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='second_account_movement_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
