# Generated by Django 3.1.5 on 2021-02-01 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210129_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 1, 18, 40, 38, 381187, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 1, 18, 40, 38, 381187, tzinfo=utc), null=True),
        ),
    ]
