# Generated by Django 3.1.5 on 2021-01-21 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210121_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='account_value_after',
            field=models.DecimalField(blank=True, decimal_places=2, default=django.utils.timezone.now, help_text='leave empty, generated automatically', max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movements',
            name='account_value_before',
            field=models.DecimalField(blank=True, decimal_places=2, default=django.utils.timezone.now, help_text='leave empty, generated automatically', max_digits=11),
            preserve_default=False,
        ),
    ]
