# Generated by Django 3.1.5 on 2021-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210209_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='second_account_movement_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
