# Generated by Django 3.1.5 on 2021-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210204_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='move_to_account_prestate',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
