# Generated by Django 3.1.5 on 2021-01-22 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210122_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='account_value',
            name='info',
            field=models.TextField(default='Default info text', max_length=500),
        ),
    ]
