# Generated by Django 3.1.5 on 2021-01-21 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210121_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_value',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movements',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
