# Generated by Django 3.1.5 on 2021-01-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210122_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_value',
            name='save_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
    ]
