# Generated by Django 3.1.5 on 2021-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210204_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='move_to_account',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'retirement540.00'), ('2', 'travel-90.00')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movements',
            name='move_to_account_prestate',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
