# Generated by Django 3.1.5 on 2021-02-04 19:59

import accounts.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210204_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Insert a negative number if you are paying', max_digits=11, validators=[accounts.functions.validate_positive]),
        ),
        migrations.AlterField(
            model_name='movements',
            name='move_to_account',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Current account342.00'), ('2', 'travel80.00')], max_length=100, null=True),
        ),
    ]
