# Generated by Django 3.1.5 on 2021-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_value_save_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_value',
            name='saving_time',
            field=models.IntegerField(default=12, help_text='Write here month amount for saving goal'),
        ),
    ]
