# Generated by Django 3.1.5 on 2021-02-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210210_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='moved_from_account',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
