# Generated by Django 3.1.5 on 2021-02-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210204_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Insert a negative number if you are paying', max_digits=11),
        ),
    ]
