# Generated by Django 3.1.5 on 2021-01-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210121_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movements',
            name='account_value_after',
        ),
        migrations.RemoveField(
            model_name='movements',
            name='account_value_before',
        ),
    ]
