# Generated by Django 3.1.5 on 2021-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210121_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='movements',
            name='account_value_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='leave empty, generated automatically', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='movements',
            name='account_value_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='leave empty, generated automatically', max_digits=11, null=True),
        ),
    ]
