# Generated by Django 3.1.5 on 2021-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210121_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='account_value_after',
            field=models.DecimalField(decimal_places=2, default=0, help_text='leave empty, generated automatically', max_digits=11),
        ),
        migrations.AlterField(
            model_name='movements',
            name='account_value_before',
            field=models.DecimalField(decimal_places=2, default=0, help_text='leave empty, generated automatically', max_digits=11),
        ),
    ]
